name: Create releases for specific tags

on:
  push:
    tags:
      - 'v-ds-*'
      - 'v-*'

permissions:
  contents: write

jobs:
  release:
    name: Create releases for matching tags
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Read and sanitize release note
        id: release_note
        run: |
          if [ -f "rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md" ]; then
            CONTENT=$(cat rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md)
            # Escape newlines and quotes for JSON
            SANITIZED=$(echo "$CONTENT" | jq -Rsa .)
            echo "note=$SANITIZED" >> $GITHUB_OUTPUT
          else
            echo "note=Release for ${TAG_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.extract_tag.outputs.tag_name }}" \
            --repo="${GITHUB_REPOSITORY}" \
            --title="${{ steps.extract_tag.outputs.tag_name }}" \
            --notes="${{ steps.release_note.outputs.note }}" \
            ./rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf