name: Create releases for specific tags

on:
  push:
    tags:
      - 'v-ai*'
      - 'v-ds*'
      - 'v-*'

permissions:
  contents: write

jobs:
  release:
    name: Create releases for matching tags
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "tag_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Read release note
        id: release_note
        run: |
          release_note_content=$(cat rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md | sed 's/^/"/;s/$/"/')
          echo "release_note=$release_note_content" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag_name }}
          release_note: ${{ env.release_note }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --notes="$release_note" \
              ./rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf
