name: Create releases for specific tags

on:
  push:
    tags:
      - 'v-ds-*'
      - 'v-*'

permissions:
  contents: write

jobs:
  release:
    name: Create releases for matching tags
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "tag_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Read and sanitize release note
        id: release_note
        run: |
          sanitized_note=$(cat rendercv_output/Putu_Gede_Pradana_Adnyana_CV.md | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')
          echo "::set-output name=release_note::$sanitized_note"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --notes="${{ steps.release_note.outputs.release_note }}" \
              ./rendercv_output/Putu_Gede_Pradana_Adnyana_CV.pdf
